language: c

compiler:
  - gcc

dist: focal
sudo: false

addons:
  apt:
    packages:
      - astyle
      - libcunit1-dev
      - libaio-dev
      - libssl-dev
      - libnuma-dev
      - uuid-dev
      - lcov
      - nasm
      - meson
      - ninja-build
      - python3-pyelftools

before_script:
  - git submodule update --init
  - export MAKEFLAGS="-j$(nproc)"

script:
  - ./scripts/check_format.sh
  - ./configure --enable-werror --without-isal --enable-debug --enable-coverage --enable-asan --with-crypto
  - make
  - ./test/unit/unittest.sh
